<script lang="ts">
  import Calendar from "@event-calendar/core";
  import TimeGrid from "@event-calendar/time-grid";
  import DayGrid from "@event-calendar/day-grid";
  import ResourceTimeGrid from "@event-calendar/resource-time-grid";
  import Interaction from "@event-calendar/interaction";
  import CList from "@event-calendar/list";
  import Modal from "./lib/Modal.svelte";
  import createEvents from "./lib/createEvents";

  import { onMount } from 'svelte'
  import { supabase } from './supabaseClient'
  import type { AuthSession } from '@supabase/supabase-js'
  import Account from './lib/Account.svelte'
  import Auth from './lib/Auth.svelte'

  let session: AuthSession

  onMount(() => {
    supabase.auth.getSession().then(({ data }) => {
      session = data.session
    })

    supabase.auth.onAuthStateChange((_event, _session) => {
      session = _session
    })


    // callback when authed
    // query userId
    // query events based on userId --- is this even necessary?? shouldn't db know who you are?
    // update myEvents and refresh view
  })
  
  let currentUserId = 1;

  function checkPerms(id) {
    // check if array
    if (Array.isArray(id)) {
      return id.includes(currentUserId) || id.includes(currentUserId.toString());
    } else {
      return id === currentUserId || id === currentUserId.toString();
    }
  }
  
  let oldColors = {}; // id -> bgcolor for mouse hover (very hacky for now)

  /* default properties of an Event object created from a selection. */
  const defaultEvent = {
    // id will be generated
    // resourceId should be current user id
    // resourceIds unused if resourceId is
    allDay: false,
    // start, end are given in selection
    title: "click me to edit!",
    editable: true, // draggable and resizable - (make false for other users)
    // startEditable // draggable (redundant.. except editable seems to be ignored so this lol
    // durationEditable // resizable
    // display: // TODO?
    backgroundColor: "#555555",
    textColor: "#ffffff",
    extendedProps: {}, // TODO !! important for more capabilities, e.g. deleting?
  }

  let ec;
  let plugins = [TimeGrid, DayGrid, ResourceTimeGrid, Interaction, CList];
  let options = {
    view: "resourceTimeGridDay",
    headerToolbar: {
      start: "prev,next today",
      center: "title",
      end: "dayGridMonth,timeGridWeek,timeGridDay,listWeek resourceTimeGridWeek",
    },
    buttonText: function (texts) {
      texts.resourceTimeGridWeek = "resources";
      return texts;
    },
    resources: [
      { id: 1, title: "You" },
      { id: 2, title: "Friend A" },
    ],
    scrollTime: "09:00:00",
    events: createEvents(),
    pointer: true,
    // views: {}
    dayMaxEvents: true,
    nowIndicator: true,
    eventDragMinDistance: 5, // not working?
    selectable: true,
    eventClick: x => {
      // TODO: "cancel" will clear... also maybe not use prompt() :)
      // TODO: delete, change color, tags, ...
      // idea: reaction on people's events
      console.log("eventClick", x);
          // // generated by copilot, explore later maybe:
          // if (x.event.extendedProps && x.event.extendedProps.url) { 
          //   window.open(x.event.extendedProps.url);
          // }

      if (!checkPerms(x.event.resourceIds)) {
        return;
      }

      ec.getOption("eventMouseLeave")({ event: x.event }); // reset bg color
      let newTitle = prompt('Event title:', x.event.title);
      x.event.title = newTitle;
      ec.updateEvent(x.event);
    },
    eventMouseEnter: x => {
      // console.log("eventMouseEnter", x);
      let currentbg = x.event.backgroundColor;
      if (!oldColors[x.event.id]) {
        oldColors[x.event.id] = currentbg;
      }
      x.event.backgroundColor = "#dddddd";
      ec.updateEvent(x.event);

    },
    eventMouseLeave: x => { // doesn't always trigger...
      // console.log("eventMouseLeave", x);
      x.event.backgroundColor = oldColors[x.event.id];
      delete oldColors[x.event.id];
      ec.updateEvent(x.event);
    },

    select: async (x) => {

      console.log("selection", x);
      let resId = x.resource.id;
      if (checkPerms(resId)) {

        

        // TODO: change to add to db and call ec.refetchEvents()
        let newEvent = { ...defaultEvent, ...x };
        newEvent.resourceId = x.resource.id;
        ec.addEvent(newEvent);

        let insertObject = { 
            
            information: newEvent,
            owner: "5a5ae255-dc27-4d94-a635-7c4978998861",
            event_start_time: x.start.toISOString(),
            event_end_time: x.end.toISOString(),
          }
        console.log(insertObject)
        const { data, error } = await supabase
          .from('Events')
          .insert(insertObject)
          .select()
        console.log(data, error)
      }
      ec.unselect();



      // myEvents.push(x);
      // ec.setOption("events", myEvents);
      // console.log(ec.getEvents());

      // create Modal component
      let modal = new Modal({
        target: document.body,
        props: {
          // event: x,
        },
      });

    },
    editable: true,
  };

  (async () => {
    const { data, error } = await supabase
      .from('Events')
      .select()
    console.log(data,error)
  })();

 async function pullEvents() {
    const { data, error } = await supabase
      .from('Events')
      .select()
    console.log(data,error);
    if (error || !data) {
      console.log("error", error);
      return;
    }
    let newEvents = data.map(x => x.information).filter(Boolean);
    ec.setOption("events", newEvents);
  };

  let formData = {
        taskName: '',
        email: '',
        message: ''
    };
    let showModal = false;
</script>

<button on:click={pullEvents}>
	Update database
</button>

<Calendar bind:this={ec} {plugins} {options} />


<div class="container" style="padding: 50px 0 100px 0">
    {#if !session}
    <Auth />
    {:else}
    <Account {session} />
    {/if}
  </div>


<button on:click={() => (showModal = true)}> show modal </button>
<Modal on:notify={sumbitFunc} bind:showModal>
  <!-- <form on:submit|preventDefault={handleSubmit}> -->
  <form on:submit|preventDefault>
    <label for="taskName">Name:</label>
    <input type="text" id="taskName" bind:value={formData.taskName} />

    <button type="submit">Submit</button>
  </form>

</Modal>

<!-- <Demo /> -->

<!-- <Modal /> -->